name: cookie_sync
description: Simple cross-platform cookie sync for Flutter WebViews.
version: 0.0.1
homepage: https://github.com/yourusername/cookie_sync
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.cookie_sync
        pluginClass: CookieSyncPlugin
      ios:
        pluginClass: CookieSyncPlugin
